(define(funcion2 lista datos)
  (if(equal? datos -1)
  (display lista)
  (funcion2 (append lista (list datos)) (read))
  )
  )
(display"Ingrese una lista de datos,la lista termina cuando ingrese -1")
(newline)
(funcion2 (list) (read))
(newline)

(define vector1 (vector funcion2))

(display"Ingrese el caracter que desea buscar:")
(newline)
(define caracter (read))
(define(funcion vector1 caracter posi posf)
  (if(< posi posf)
   (if(equal? (vector-ref vector1 posi) caracter)
   (begin
   (display"El caracter se encuentra en la posicion:")
   (newline)
    posi
    )
   (funcion vector1 caracter (+ posi 1) posf )
   )
   (display"El vector no se encuentra en la lista")
   )
)
(funcion vector1 caracter 0 (vector-length vector1))