;Hacer una función que devuelva el promedio de los datos de una lista de enteros.
(display"Ingrese una lista de enteros la lista termina cuando ingrese 0:")
(newline)
(define(lista1 lista leer)
  (if(equal? leer 0)
     (display lista)
     (lista1(append lista (list leer)) (read))
   )
)
(lista1 (list) (read))
(newline)
(display"El promedio de los datos de la lista es:")
(newline)

(define lista1 (list 10 10 10))
(define(lista2 lista1 tamaño posi cont)
  (if(< posi tamaño)
  (lista2 lista1 tamaño (+ posi 1) (+ (list-ref lista1 posi) cont))
   (/ cont  (length lista1))
  )
)
(lista2 lista1 (length lista1) 0 0)