(require (lib "graphics.ss" "graphics"))
(open-graphics)
(define w (open-viewport "HOLA" 680 680))
(define(lineaI x y)
  (if(<= x 580)
     (begin
     ((draw-solid-rectangle w)(make-posn x y) 40 40 "black")
     ((draw-solid-rectangle w)(make-posn (+ x 40)y) 40 40 "blue")
     (lineaI(+ x 80 )y)
     )
  )
  )
(define(lineaP x y)
  (if(<= x 580)
     (begin
       ((draw-solid-rectangle w)(make-posn x y) 40 40 "blue")
       ((draw-solid-rectangle w)(make-posn (+ x 40)y) 40 40 "black")
       (lineaP(+ x 80)y)
       )
     )
  )
(define(cuadroc y)
  (if(<= y 580)
     (begin
       (lineaI 20 y)
       (lineaP 20 (+ y 40))
       (cuadroc (+ y 80))
       )
     )
  )
(cuadroc 20)
