;Construir un programa que lea un string con solo caracteres numéricos y devuelva el número ;que representa.
(define (strignum cadena)
(auxstrignum cadena 0 0)
)
(define(auxstrignum cadena nvo_nro control)
(begin
(if (< control (- (string-length cadena) 1))
(auxstrignum cadena (+ (* nvo_nro 10) (* (ascii (substring cadena control (+ control 1))) 10)) (+ control 1))
(+ nvo_nro (ascii (substring cadena control (string-length cadena))))
)
)
)
(define (ascii cadena)
(cond
( (string=? cadena "0") 0)
( (string=? cadena "1") 1)
( (string=? cadena "2") 2)
( (string=? cadena "3") 3)
( (string=? cadena "4") 4)
( (string=? cadena "5") 5)
( (string=? cadena "6") 6)
( (string=? cadena "7") 7)
( (string=? cadena "8") 8)
( (string=? cadena "9") 9)
)
)
; Ejemplo:
(display"Ingrese solo caracteres numericos:")
(newline)
(strignum (read-line))
